author: meta1203
database: true
main: me.meta1203.plugins.sakuracoin.Sakuracoinish
name: Sakuracoinish
url: https://github.com/ohac
softdepend: [Vault]
load: startup
version: '1.1'
commands:
  deposit:
    description: 'Deposit money through Bitcoin address'
  money:
    description: 'List your in-game money balance'
  withdraw:
    description: 'Withdraw money to a Bitcoin address'
  transact:
    description: 'Send in-game money to player'
  sakuracoin:
    description: 'Print testing info'
  syscheck:
    description: 'Check Satoshis system health'
  credit:
    description: 'Credit in-game money to player'
  debit:
    description: 'Debit in-game money from player'
  auction:
    description: 'In-Game auction controller.'
permissions:
  sakuracoin.admin:
    description: 'Permission for Satoshis /satoshis'
  sakuracoin.withdraw:
    description: 'Permission for Satoshis /withdraw'
    default: 'true'
  sakuracoin.deposit:
    description: 'Permission for Satoshis /deposit'
    default: 'true'
  sakuracoin.transact:
    description: 'Permission for Satoshis /transact'
  sakuracoin.money:
    description: 'Permission for Satoshis /money'
    default: 'true'
  sakuracoin.info:
    description: 'Permission for Satoshis /syscheck'
  sakuracoin.credit:
    description: 'Permission for Satoshis /credit'
  sakuracoin.debit:
    description: 'Permission for Satoshis /debit'
  sakuracoin.auction:
    description: 'Permissions for Satoshis /auction'
    default: 'true'
